# Generated by Django 4.1.1 on 2022-09-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='like_count'),
        ),
    ]
